"use strict";
/* Voluntary session arcs connecting exploration, building, creatures and lessons. */
var Expeditions = (function () {
  var RELICS = [
    {id:"mosswing",icon:"🦋",name:"Mosswing Pin",tale:"A sign that the wild paths know your name."},
    {id:"glowglass",icon:"🔆",name:"Glowmoth Glass",tale:"It holds the soft light of a befriended glowmoth."},
    {id:"hearthkey",icon:"🗝️",name:"Hearth Key",tale:"Made for a Keeper who turns materials into a home."},
    {id:"roofstar",icon:"⭐",name:"Rafter Star",tale:"It shines over careful builders and crooked first drafts."},
    {id:"compassrose",icon:"🧭",name:"Cloud Compass",tale:"Its needle points toward what you have not found yet."},
    {id:"storyfeather",icon:"🪶",name:"Story Feather",tale:"A record of a trail followed with a curious mind."}
  ];
  var DEFS = [
    {id:"wild",icon:"🦋",name:"Whispering Wilds",blurb:"Gather from the isle, befriend one creature, and uncover a learning discovery.",stages:[{kind:"gather",need:3,text:"Gather 3 finds from the isle"},{kind:"creature",need:1,text:"Befriend one island creature"},{kind:"learn",need:1,text:"Complete a learning discovery"}],relics:["mosswing","glowglass"]},
    {id:"maker",icon:"🏠",name:"The Keeper's Hearth",blurb:"Build something useful, gather fresh supplies, and use learning to kindle its light.",stages:[{kind:"build",need:2,text:"Place 2 building pieces"},{kind:"gather",need:2,text:"Gather 2 fresh supplies"},{kind:"learn",need:1,text:"Complete a learning discovery"}],relics:["hearthkey","roofstar"]},
    {id:"trail",icon:"🌠",name:"Starlight Trail",blurb:"Follow a trail of action, learning, and friendship across your current isle.",stages:[{kind:"gather",need:2,text:"Gather 2 clues from the isle"},{kind:"learn",need:1,text:"Solve the starlight discovery"},{kind:"creature",need:1,text:"Share the discovery with a creature"}],relics:["compassrose","storyfeather"]}
  ];
  function ensure(save){save=save||Store.data;if(!save.expeditions)save.expeditions={active:null,started:0,completed:0,abandoned:0,totalMs:0,relics:[],history:[]};var e=save.expeditions;if(!Array.isArray(e.relics))e.relics=[];if(!Array.isArray(e.history))e.history=[];return e;}
  function defFor(id){return DEFS.find(function(d){return d.id===id;});}
  function relicFor(id){return RELICS.find(function(r){return r.id===id;});}
  function active(){return ensure().active;}
  function stage(){var a=active(),d=a&&defFor(a.id);return d&&d.stages[a.stage];}
  function emit(name,detail){try{window.dispatchEvent(new CustomEvent("lumen:"+name,{detail:detail}));}catch(e){}}
  function progressText(){var a=active(),s=stage(),d=a&&defFor(a.id);return !a||!s?"🧭 Choose an adventure":d.icon+" "+s.text+" · "+Math.min(a.count,s.need)+"/"+s.need;}
  function updateHud(){var el=document.getElementById("expedition-hud");if(!el)return;el.textContent=progressText();el.style.display=Store.data.firstDiscovery&&!Store.data.firstDiscovery.done?"none":"block";}
  function start(id){var d=defFor(id),e=ensure();if(!d)return false;if(e.active)e.abandoned=(e.abandoned||0)+1;e.active={id:id,stage:0,count:0,isle:Store.data.player.isle,startedAt:Date.now()};e.started=(e.started||0)+1;Store.saveNow();updateHud();emit("expedition-start",{id:id,isle:e.active.isle});UI.closeOverlay();UI.toast(d.icon+" "+d.name+" begun! "+d.stages[0].text,4200);return true;}
  function record(kind,amount,detail){var a=active(),s=stage();if(!a||!s||s.kind!==kind)return false;a.count=Math.min(s.need,a.count+(amount||1));emit("expedition-progress",{id:a.id,stage:a.stage,kind:kind,count:a.count,need:s.need,detail:detail||{}});if(a.count>=s.need){var d=defFor(a.id);a.stage+=1;a.count=0;if(a.stage>=d.stages.length){finish(d,a);return true;}Store.saveNow();updateHud();UI.toast("✨ Trail step complete! Next: "+d.stages[a.stage].text,4200);}else{Store.save();updateHud();}return true;}
  function nextRelic(d,e){for(var i=0;i<d.relics.length;i++)if(e.relics.indexOf(d.relics[i])<0)return relicFor(d.relics[i]);return null;}
  function finish(d,a){var e=ensure(),relic=nextRelic(d,e),elapsed=Math.max(0,Date.now()-a.startedAt);if(relic)e.relics.push(relic.id);e.completed=(e.completed||0)+1;e.totalMs=(e.totalMs||0)+elapsed;e.history.push({id:d.id,isle:a.isle,at:Date.now(),relic:relic&&relic.id});e.history=e.history.slice(-30);e.active=null;Game.grantSparks(10);Game.grantXP(20);Store.saveNow();updateHud();Game.burst(Player.position.x,Player.position.y+1,Player.position.z,0xffdf78,32);emit("expedition-complete",{id:d.id,isle:a.isle,relic:relic&&relic.id,durationMs:elapsed});setTimeout(function(){showComplete(d,relic);},180);}
  function stageHtml(d,a){return d.stages.map(function(s,i){var cls=i<a.stage?"done":i===a.stage?"active":"",count=i<a.stage?s.need:i===a.stage?a.count:0;return "<div class='expedition-step "+cls+"'>"+(i<a.stage?"✓ ":i===a.stage?"➜ ":"○ ")+s.text+" <b>"+count+"/"+s.need+"</b></div>";}).join("");}
  function show(){var a=active();if(a){showActive(a);return;}UI.openOverlay("<div class='ch-title'>🧭 Keeper Expeditions</div><div class='ch-sub'>Choose the kind of adventure you want today. There is no timer, and your trail saves if you leave.</div><div class='world-list'>"+DEFS.map(function(d){return "<button class='world-card' data-exp-start='"+d.id+"'><span class='world-emoji'>"+d.icon+"</span><span class='world-name'>"+d.name+"</span><span class='world-req'>"+d.blurb+"</span></button>";}).join("")+"</div><button class='big-btn' id='exp-journal'>📖 Field Journal</button><button class='ghost-btn' id='exp-back'>Back to exploring</button>");document.querySelectorAll("[data-exp-start]").forEach(function(b){b.addEventListener("click",function(){start(b.dataset.expStart);});});document.getElementById("exp-journal").addEventListener("click",showJournal);document.getElementById("exp-back").addEventListener("click",UI.closeOverlay);}
  function showActive(a){var d=defFor(a.id),s=stage();UI.openOverlay("<div class='ch-title'>"+d.icon+" "+d.name+"</div><div class='ch-sub'>One step at a time. Your progress is saved.</div>"+stageHtml(d,a)+(s.kind==="learn"?"<button class='big-btn' id='exp-learn'>✨ Make the discovery</button>":"")+"<button class='big-btn' id='exp-journal'>📖 Field Journal</button><button class='ghost-btn' id='exp-back'>Keep exploring</button><button class='ghost-btn' id='exp-change'>Choose a different adventure</button>");if(document.getElementById("exp-learn"))document.getElementById("exp-learn").addEventListener("click",function(){UI.showChallenge("node",function(result){if(result.correct&&!result.skipped&&!result.nolesson)record("learn",1);else if(result.nolesson){UI.toast("A grown-up can choose lessons in Parents → Assignments.",4500);showActive(active());}},"✨ "+d.name+" discovery");});document.getElementById("exp-journal").addEventListener("click",showJournal);document.getElementById("exp-back").addEventListener("click",UI.closeOverlay);document.getElementById("exp-change").addEventListener("click",function(){var e=ensure();e.abandoned=(e.abandoned||0)+1;e.active=null;Store.saveNow();updateHud();show();});}
  function showComplete(d,relic){UI.openOverlay("<div class='ch-title'>🌟 Expedition complete!</div><div class='sentence-text'>You completed "+d.name+" and earned 10 sparks and 20 light.</div>"+(relic?"<div class='journal-relic'>"+relic.icon+" "+relic.name+"<div class='ch-sub'>"+relic.tale+"</div></div>":"<div class='ch-sub'>Your journal already holds both discoveries from this trail. Your experience still counts.</div>")+"<button class='big-btn' id='exp-journal'>📖 Open Field Journal</button><button class='ghost-btn' id='exp-back'>Back to the isle</button>");document.getElementById("exp-journal").addEventListener("click",showJournal);document.getElementById("exp-back").addEventListener("click",UI.closeOverlay);}
  function showJournal(){var e=ensure(),avg=e.completed?Math.round(e.totalMs/e.completed/60000):0;UI.openOverlay("<div class='ch-title'>📖 "+Store.profile.name+"'s Field Journal</div><div class='ch-sub'>Every discovery remembers an adventure you chose and completed.</div><div class='journal-grid'>"+RELICS.map(function(r){var got=e.relics.indexOf(r.id)>=0;return "<div class='journal-relic "+(got?"":"locked")+"'>"+(got?r.icon:"❔")+"<br>"+(got?r.name:"Undiscovered")+(got?"<div class='ch-sub'>"+r.tale+"</div>":"")+"</div>";}).join("")+"</div><div class='ch-sub'>"+e.completed+" completed · "+e.started+" started"+(avg?" · about "+avg+" minutes each":"")+"</div>"+(e.completed?"<button class='big-btn' id='exp-postcard'>🖼️ Grown-up: hold to save a Keeper Postcard</button>":"")+"<button class='big-btn' id='exp-choose'>🧭 "+(active()?"Current expedition":"Choose an adventure")+"</button><button class='ghost-btn' id='exp-back'>Back</button>");if(document.getElementById("exp-postcard"))UI.holdToOpen(document.getElementById("exp-postcard"),function(){Parent.authorize(savePostcard,showJournal);});document.getElementById("exp-choose").addEventListener("click",show);document.getElementById("exp-back").addEventListener("click",UI.closeOverlay);}
  function postcardData(){var e=ensure(),last=e.history[e.history.length-1]||{},d=defFor(last.id)||DEFS[0],r=relicFor(last.relic),c=document.createElement("canvas");c.width=1200;c.height=630;var x=c.getContext("2d"),game=window.__dbg&&window.__dbg.renderer&&window.__dbg.renderer.domElement,grad=x.createLinearGradient(0,0,1200,630);grad.addColorStop(0,"#263558");grad.addColorStop(1,"#6ca986");x.fillStyle=grad;x.fillRect(0,0,1200,630);if(game)try{x.globalAlpha=.38;x.drawImage(game,470,0,730,630);x.globalAlpha=1;}catch(ignore){}x.fillStyle="rgba(253,246,232,.94)";x.beginPath();x.roundRect(60,58,660,514,28);x.fill();x.fillStyle="#3a4a68";x.font="800 38px system-ui";x.fillText("LUMEN ISLES · KEEPER POSTCARD",105,125);x.font="64px system-ui";x.fillText(Store.profile.emoji||"✨",105,215);x.font="800 48px system-ui";x.fillText(Store.profile.name,190,205);x.font="800 34px system-ui";x.fillText(d.icon+" "+d.name,105,290);x.font="700 27px system-ui";x.fillStyle="#76694f";x.fillText("Expedition "+e.completed+" complete",105,340);x.font="800 35px system-ui";x.fillStyle="#3f8c53";x.fillText(r?r.icon+" "+r.name:"🌟 Seasoned Keeper",105,415);x.font="700 23px system-ui";x.fillStyle="#76694f";x.fillText("Explore · Build · Learn · Shine",105,505);x.fillText("jlevins2011.github.io/HS-Game-v1",105,540);return c.toDataURL("image/png");}
  function savePostcard(){var a=document.createElement("a");a.href=postcardData();a.download="lumen-isles-"+Store.profile.name.toLowerCase().replace(/[^a-z0-9]+/g,"-")+"-postcard.png";a.click();UI.toast("🖼️ Keeper Postcard saved!",3000);}
  function populate(add,def){var e=ensure(),visits=e.history.filter(function(h){return h.isle===def.id;}).length;if(!visits)return;var spawn=def.spawn||{x:Terrain.CX,z:Terrain.CZ};add("keepermark",spawn.x+5,spawn.z+4,{id:"keeper-expedition-mark",variant:Math.min(5,visits-1)});}
  Objects.TYPES.keepermark={name:"Keeper Trail Marker",clearRadius:3,dynamic:function(o){var g=new Geo.Builder();g.cyl(.8,.65,.35,6,0x77738b,{},.08,0);g.cyl(.12,.09,2.3,6,0xd7c17e,{y:.35},.05,0);for(var i=0;i<Math.min(6,o.variant+1);i++){var a=i*Math.PI/3;g.blob(.16,0xffdd74,{x:Math.cos(a)*.55,y:2.65,z:Math.sin(a)*.55},.08,0);}var mesh=g.build();mesh.position.set(o.x,o.y,o.z);return mesh;}};
  function summary(save){var e=ensure(save),s=save.stats.sessions||{count:0,totalMs:0};return {started:e.started||0,completed:e.completed||0,relics:e.relics.length,avgSessionMin:s.count?Math.round(s.totalMs/s.count/60000):0};}
  return {show:show,showJournal:showJournal,record:record,updateHud:updateHud,populate:populate,summary:summary,postcardData:postcardData,_defs:DEFS};
})();
